@echo off
echo Removing server folder from git...
git rm -r --cached server
echo Adding changes...
git add .
echo Committing...
git commit -m "Remove-server-folder-use-serverless"
echo Pushing...
git push origin main
echo Done! Check Vercel in 2 minutes.
pause
